dtb-$(CONFIG_ARCH_ROCKCHIP) += rk3368-evb-act8846.dtb
dtb-$(CONFIG_ARCH_ROCKCHIP) += rk3368-geekbox.dtb
dtb-$(CONFIG_ARCH_ROCKCHIP) += rk3368-r88.dtb
dtb-$(CONFIG_ARCH_ROCKCHIP) += rk3399-evb.dtb
dtb-$(CONFIG_ARCH_ROCKCHIP) += rk3399-gru-bob-r0.dtb
dtb-$(CONFIG_ARCH_ROCKCHIP) += rk3399-gru-bob-r2.dtb
dtb-$(CONFIG_ARCH_ROCKCHIP) += rk3399-gru-gru-r1.dtb
dtb-$(CONFIG_ARCH_ROCKCHIP) += rk3399-gru-gru-r2.dtb
dtb-$(CONFIG_ARCH_ROCKCHIP) += rk3399-gru-kevin-r5.dtb
dtb-$(CONFIG_ARCH_ROCKCHIP) += rk3399-gru-kevin-r6.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
